close all;
clear all;
t= 0:0.01:6*pi;
figure(1);
subplot(2,2,1);
plot(t, sin(t));
hold on;
plot(t,sin(t+2));
ylabel("amplitude");
xlabel("time");
title("shifting of sin(t)")
subplot(2,2,2);
plot(t,sin(t));
hold on;
plot(t,sin(-t));
xlabel("time");
ylabel("amplitude");
title("inverse of sin t")
subplot(2,2,3);
plot(t,sin(t));
hold on;
plot(t , sin(2*t));
xlabel("time");
ylabel("amplitude");
title("scaling of sin t");
subplot(2,2,4);
plot(t,sin(t));
hold on;
plot(t,-sin(t));
xlabel("time");
ylabel("amplitude");
title("-ve of sin t");
