close all;
clear all;
t= 0:0.01:6*pi;
figure(1);
subplot(2,3,1);
plot(t, sin(t));
hold on;
plot(t,3*sin(t*0.5));
ylabel("amplitude");
xlabel("time");
title("shifting and scaling");
subplot(2,3,2);
plot(t,sin(t));
hold on;
plot(t,sin(2*t+3));
xlabel("time");
ylabel("amplitude");
title("shifting and scaling");
subplot(2,3,3);
plot(t,sin(t));
hold on;
plot(t , sin(0.5*t-3));
xlabel("time");
ylabel("amplitude");
title("shifting and scaling");
subplot(2,3,4);
plot(t,sin(t));
hold on;
plot(t,2*sin(-3*t-4));
xlabel("time");
ylabel("amplitude");
title("shifting and scaling");
subplot(2,3,5);
plot(t,sin(t));
hold on;
plot(t,-2*sin(-3*(t+2)+1));
xlabel("time");
ylabel("amplitude");
title("shifting and scaling ");

